version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_project
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pagoda
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_project
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@isw-fnt.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
