spring.datasource.url=jdbc:postgresql://localhost:5433/pagoda
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080